### PR TITLE
abstracting collection owner to localsettings

### PR DESCRIPTION
**Pull request by ghukill**
Abstracts out what appears to be a hard-coded Fedora object owner from the collections view.

Adds a new setting to `localsettings` for an optional collection owner filter.  If that variable is left blank, no filtering is done.

### CODE REVIEW

**Comment by ghukill** [comment]
Sorry for the confusing pull request - pushed another change to our fork that appears to have worked its way into this PR.  It's related to generating IIIF URLs from the `PageImage` class.  

Specifically, a small change [here](https://github.com/WSULib/readux/blob/b54b702f01c2302a0663721129ed7b6df09a5ca9/readux/books/views.py#L920).

Noticed this by logging what [URL is generated here](https://github.com/WSULib/readux/blob/b54b702f01c2302a0663721129ed7b6df09a5ca9/readux/books/views.py#L845).

We were having `info.json` requests go through just fine, but image requests were failing.  This is going through a proxy on _our_ end as well.  It looks like the IIIF requests coming out of Readux were slightly different for the two; image requests had an extra slash `/` after the image id.

example `info.json` URL:
```
http://localhost/loris/IMAGE_ID_HERE/info.json
```
example image URL:
```
http://localhost/loris/IMAGE_ID_HERE//0,0,1708,2828/107,/0/default.jpg
```

You can see the double slashes in the image URL.  My guess is that this wasn't a problem before we implemented our own proxy, that it was a bit more tolerant of extra slashes.  But with our new proxy, that extra slash matters.

**Comment by rlskoeser** [comment]
Thanks for the fixes!  (Sorry it took me so long to get around to merging this PR.)

I made a slight tweak, so the collection owner filter is only applied if it's present and set, and the code shouldn't choke if the value isn't configured at all.  Also documented the config change n the deploy notes.  I don't think these changes should affect anything with your setup.

**Comment by ghukill** [comment]
Thanks for integrating and adding those catches, was clearly juggling a few different threads at the time and neglected to fall back on no-filtering, which is a great idea.  Will pull those changes and take it for a spin!

**Comment by rlskoeser** [comment]
@ghukill be advised, current develop code is broken for displaying images - I switched readux over to using piffle and promptly found a bug!  Working on a fix when I get the chance, hope to have a fix out soon.

**Pull request merged**
